import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "영고",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`antialiased`}
        style={{
          display: "flex",
          justifyContent: "center",
          backgroundColor: "#f5f5f5", // 배경 회색톤
          minHeight: "100vh",
          height: "100%",
        }}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
